# -*- coding: utf-8 -*-
"""ex1_0902.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFD8aMOWwu31BlYdxjwNncsAOuKNK63A
"""

x = "awesome"

def myfunc():
  x = "1111"
  print("Python is " + x)

myfunc()

x = "awesome" #전역

def myfunc(): #이거는 myfunc를 정의하는부분
  x = "fantastic" #지역 #fantastic은 함수 안에서 태어난 애라 함수가 실행됐을때만 출력됨
  print("Python is " + x)

myfunc() #이때 실행되는거임.

print("Python is " + x)

x = "pretty"
def myfunc():
    global x
    x = "fantastic"

myfunc()
print("Python is " + x)

텍스트 유형:	str
숫자 유형:	int(#정수), float, complex(#숫자랑 정수)
시퀀스 유형:	list(#데이터 타입이 섞여있는 리스트), tuple, range
매핑 유형:	dict(#딕셔너리)
세트 유형:	set,frozenset
부울 유형:	bool(#참 거짓 판별)
이진 유형:	bytes, bytearray, memoryview
없음 유형:	NoneType

a = "Hello, World!"
print(a[1])

a = "Hello, World!"
print(len(a)) #legnth 길이는 빈칸까지 셈

txt = "The best things in life are free!"
print("free" in txt) #txt에 free가 있느냐를 물어보는 것임

print("AI 서비스 백엔드 프로그래밍 실무")
print("=============================")
print("파이썬 기본 문법, 시간:8")
print("클래스, 시간:8")
print("데코레이터, 시간:8")
print("예외 처리, 시간:8")
print("로깅, 시간:8")

print("AI 서비스 백엔드 프로그래밍 실무")
print("=============================")

topics = ["파이썬 기본 문법", "클래스", "데코레이터", "예외 처리", "로깅"]

for topic in topics:
    print(f"{topic}, 시간:8")

print("AI 서비스 백엔드 프로그래밍 실무")
print("=============================")
x = "시간:8"
print(f"파이썬 기본 문법, {x}")
print(f"클래스, {x}")
print(f"데코레이터, {x}")
print(f"예외 처리, {x}")
print(f"로깅, {x}")

mylist = ["apple", "6", "banana", "3"]
print(mylist[2])

mylist = ["apple", "6", "banana", "3", "cherry", "orange", "kiwi", "melon", "mango"]
print(mylist[:5])

def myfunc():
  print("hello")

myfunc()

#함수 선언
def cel(f):
  return(f - 32) * 5 /9

#함수 실행+출력
print(cel(77))

#사칙연산
def f1(su):
  return su + 100
def f2(su):
  return su -50
def f3(su):
  return su * 5
def f4(su):
  return su /5

print(f1(5))
print(f2(5))
print(f3(5))
print(f4(5))

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

