# -*- coding: utf-8 -*-
"""ex4_0910.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoHnSgpFNoy7tT8CdRbigwLAMOker8ci
"""

myfamily = {
    "child1" : {},
    "child2" : {},
    "child3" : {}
}

print(myfamily)

myfamily2 = {
    "child1" : "이름1",
    "child2" : "이름2",
    "child3" : "이름3"
}

print(myfamily2)

"""파이썬 딕셔너리 타입 접근하기"""

myfamily4 = {
    "child1" : {"이름" : "엘리스", "나이": "9"},
    "child2" : {"이름" : "체리", "나이": "7"},
    "child3" : {"이름" : "덜핀", "나이": "5"}
}

print(myfamily4)
print(myfamily4["child2"])
print(myfamily4["child2"]["이름"])
myfamily4["child2"]["이름"] = "알리스"
print(myfamily4)

ch1 = "엘리스"
ch2 = "체리"
ch3 = "덜핀"
print(ch1, ch2, ch3)

ch1 = {"이름": "엘리스", "취미": "피아노"}
ch2 = {"이름": "체리", "취미": "수영"}
ch3 = {"이름": "덜핀", "취미": "축구"}
print(ch1, ch2, ch3)

yourfamily = {}

yourfamily = {
    "ch1": ch1,
    "ch2": ch2,
    "ch3": ch3
}

print(yourfamily)

#파이썬 IF
a = 33
b = 200
if b > a:
  print("b는 a보다 크다")

#람다
if b > a: print("b는 a보다 크다")

c = 330
d = 200
if d < c:
  #if문에 해당되지 않으면 실행되지 않음
  print("c는 d보다 크다")

#람다
print("D") if d > c else print("False")

num1 = 50
num2 = 100

if num2 > num1:
  print("100은 50보다 큽니다")

elif num1 == num1:
  print("두 수는 같습니다")

#elif는 조건 두개 이상
score = 75

if score >= 90:
  print("A")
elif score >= 80:
  print("B")
elif score >= 70:
  print("C")
elif score >= 60:
  print("D")
else: #else는 맨 마지막에 넣기
  print("F")

num = num + 1 #++num
num = num - 1 #--num

num = num + 2 # num +=2

#match

day = 4
match day:
  case 1:
    print("Monday")
  case 2:
    print("Tuesday")
  case 3:
    print("Wednesday")
  case 4:
    print("Thursday")
  case 5:
    print("Friday")
  case 6:
    print("Saturday")
  case 7:
    print("Sunday")

day = 4
match day:
  case 6:
    print("Today is Saturday")
  case 7:
    print("Today is Sunday")
  case _:
    print("Looking forward to the Weekend")

day = 4
match day:
  case 1 | 2 | 3 | 4 | 5:
    print("Today is a weekday")
  case 6 | 7:
    print("I love weekends!")

#while loop: 조건이 참인 동안 일련의 명령문을 계속하여 실행 --> 빠져나가는 방법을 먼저 생각해야함

i = 0
while i < 6:
  i = i + 1
  print(i)

i = 0
while i < 6:
  if i == 3:
    break
  i = i + 1
  print(i)

i = 0
while i < 6:
  i += 1
  if i == 3:
    continue
  print(i)

#for문 갯수 정해져있을때 많이 씀
#while은 갯수 안정해져있을때 많이 씀
#for in문은 갯수 왔다갔다 해도 오버플로우의 위험이 없음

adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)

